language: python
dist: trusty
addons:
  sonarcloud:
    organization: "slackcc-github" # the key of the org you chose at step #3
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - sonar-scanner
#  - pytest # or py.test for Python versions 3.5 and below
